adminUser:
  password: vault:jx-aps-howlernimble/adminUser:password
  username: admin
dashboardAuthID: vault:jx-aps-howlernimble:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:jx-aps-howlernimble:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:jx-aps-howlernimble/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:jx-aps-howlernimble/prow:hmacToken
